title: deer-hunt GitHub Page
description: deer-hunt GitHub Page.
url: https://deer-hunt.github.io/
baseurl: ""
theme: "minimal-mistakes-jekyll"

logo: https://avatars.githubusercontent.com/u/188069631

plugins:
  - jekyll-feed
